# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ausgaben.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ausgaben(object):
    def setupUi(self, ausgaben):
        ausgaben.setObjectName("ausgaben")
        ausgaben.resize(567, 469)
        ausgaben.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(ausgaben)
        self.centralwidget.setObjectName("centralwidget")
        self.ausgaben_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.ausgaben_2.setGeometry(QtCore.QRect(0, 0, 561, 421))
        self.ausgaben_2.setObjectName("ausgaben_2")
        self.uebsicht = QtWidgets.QWidget()
        self.uebsicht.setObjectName("uebsicht")
        self.tableAusgaben = QtWidgets.QTableView(self.uebsicht)
        self.tableAusgaben.setGeometry(QtCore.QRect(10, 10, 541, 301))
        self.tableAusgaben.setObjectName("tableAusgaben")
        self.widget = QtWidgets.QWidget(self.uebsicht)
        self.widget.setGeometry(QtCore.QRect(120, 330, 206, 29))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.overview = QtWidgets.QPushButton(self.widget)
        self.overview.setObjectName("overview")
        self.horizontalLayout.addWidget(self.overview)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.ausgaben_2.addTab(self.uebsicht, "")
        self.hinzufuegen = QtWidgets.QWidget()
        self.hinzufuegen.setObjectName("hinzufuegen")
        self.widget1 = QtWidgets.QWidget(self.hinzufuegen)
        self.widget1.setGeometry(QtCore.QRect(20, 21, 148, 164))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verwendungszweck = QtWidgets.QLineEdit(self.widget1)
        self.verwendungszweck.setObjectName("verwendungszweck")
        self.verticalLayout_2.addWidget(self.verwendungszweck)
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.date = QtWidgets.QDateEdit(self.widget1)
        self.date.setObjectName("date")
        self.verticalLayout_2.addWidget(self.date)
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.money = QtWidgets.QDoubleSpinBox(self.widget1)
        self.money.setObjectName("money")
        self.verticalLayout_2.addWidget(self.money)
        self.widget2 = QtWidgets.QWidget(self.hinzufuegen)
        self.widget2.setGeometry(QtCore.QRect(180, 21, 95, 81))
        self.widget2.setObjectName("widget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.submit = QtWidgets.QPushButton(self.widget2)
        self.submit.setObjectName("submit")
        self.verticalLayout.addWidget(self.submit)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.ausgaben_2.addTab(self.hinzufuegen, "")
        ausgaben.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ausgaben)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 567, 25))
        self.menubar.setObjectName("menubar")
        ausgaben.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ausgaben)
        self.statusbar.setObjectName("statusbar")
        ausgaben.setStatusBar(self.statusbar)

        self.retranslateUi(ausgaben)
        self.ausgaben_2.setCurrentIndex(1)
        self.pushButton_2.clicked.connect(self.verwendungszweck.clear)
        self.pushButton_2.clicked.connect(self.money.clear)
        self.pushButton_4.clicked.connect(self.ausgaben_2.close)
        QtCore.QMetaObject.connectSlotsByName(ausgaben)

    def retranslateUi(self, ausgaben):
        _translate = QtCore.QCoreApplication.translate
        ausgaben.setWindowTitle(_translate("ausgaben", "Ausgaben"))
        self.overview.setText(_translate("ausgaben", "Übersicht"))
        self.pushButton_4.setText(_translate("ausgaben", "Abbrechen"))
        self.ausgaben_2.setTabText(self.ausgaben_2.indexOf(self.uebsicht), _translate("ausgaben", "Uebersicht"))
        self.label.setText(_translate("ausgaben", "Verwendungszweck"))
        self.label_2.setText(_translate("ausgaben", "Datum"))
        self.label_3.setText(_translate("ausgaben", "Preis in Euro"))
        self.submit.setText(_translate("ausgaben", "Eintragen"))
        self.pushButton_2.setText(_translate("ausgaben", "Abbrechen"))
        self.ausgaben_2.setTabText(self.ausgaben_2.indexOf(self.hinzufuegen), _translate("ausgaben", "Ausgabe hinzufuegen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ausgaben = QtWidgets.QMainWindow()
    ui = Ui_ausgaben()
    ui.setupUi(ausgaben)
    ausgaben.show()
    sys.exit(app.exec_())

